-- APP SUBMAP (SUPER + A enters, single key toggles, ESC exits)
hl.define_submap("app", function()
  hl.bind("d", hl.dsp.workspace.toggle_special("discord"))
  hl.bind("d", hl.dsp.submap("reset"))
  hl.bind("s", hl.dsp.workspace.toggle_special("obs"))
  hl.bind("s", hl.dsp.submap("reset"))
  hl.bind("o", hl.dsp.workspace.toggle_special("obsidian"))
  hl.bind("o", hl.dsp.submap("reset"))
  hl.bind("a", hl.dsp.workspace.toggle_special("anki"))
  hl.bind("a", hl.dsp.submap("reset"))
  hl.bind("m", hl.dsp.workspace.toggle_special("moonlight"))
  hl.bind("m", hl.dsp.submap("reset"))
  hl.bind("q", hl.dsp.workspace.toggle_special("qutebrowser"))
  hl.bind("q", hl.dsp.submap("reset"))
  hl.bind("t", hl.dsp.workspace.toggle_special("spotify"))
  hl.bind("t", hl.dsp.submap("reset"))
  hl.bind("w", hl.dsp.workspace.toggle_special("whatsapp"))
  hl.bind("w", hl.dsp.submap("reset"))

  hl.bind("SHIFT + D", hl.dsp.window.move({ workspace = "special:discord" }))
  hl.bind("SHIFT + D", hl.dsp.submap("reset"))
  hl.bind("SHIFT + S", hl.dsp.window.move({ workspace = "special:obs" }))
  hl.bind("SHIFT + S", hl.dsp.submap("reset"))
  hl.bind("SHIFT + O", hl.dsp.window.move({ workspace = "special:obsidian" }))
  hl.bind("SHIFT + O", hl.dsp.submap("reset"))
  hl.bind("SHIFT + A", hl.dsp.window.move({ workspace = "special:anki" }))
  hl.bind("SHIFT + A", hl.dsp.submap("reset"))
  hl.bind("SHIFT + M", hl.dsp.window.move({ workspace = "special:moonlight" }))
  hl.bind("SHIFT + M", hl.dsp.submap("reset"))
  hl.bind("SHIFT + Q", hl.dsp.window.move({ workspace = "special:qutebrowser" }))
  hl.bind("SHIFT + Q", hl.dsp.submap("reset"))
  hl.bind("SHIFT + T", hl.dsp.window.move({ workspace = "special:spotify" }))
  hl.bind("SHIFT + T", hl.dsp.submap("reset"))
  hl.bind("SHIFT + W", hl.dsp.window.move({ workspace = "special:whatsapp" }))
  hl.bind("SHIFT + W", hl.dsp.submap("reset"))

  hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)

hl.bind("SUPER + A", hl.dsp.submap("app"))
