-- APP SUBMAP (SUPER + N enters, single key toggles, ESC exits)
hl.define_submap("app", function()
  hl.bind("d", hl.dsp.focus({ workspace = "name:discord" }))
  hl.bind("d", hl.dsp.submap("reset"))
  hl.bind("s", hl.dsp.focus({ workspace = "name:obs" }))
  hl.bind("s", hl.dsp.submap("reset"))
  hl.bind("o", hl.dsp.focus({ workspace = "name:obsidian" }))
  hl.bind("o", hl.dsp.submap("reset"))
  hl.bind("a", hl.dsp.focus({ workspace = "name:anki" }))
  hl.bind("a", hl.dsp.submap("reset"))
  hl.bind("m", hl.dsp.focus({ workspace = "name:moonlight" }))
  hl.bind("m", hl.dsp.submap("reset"))
  hl.bind("q", hl.dsp.focus({ workspace = "name:qutebrowser" }))
  hl.bind("q", hl.dsp.submap("reset"))
  hl.bind("t", hl.dsp.focus({ workspace = "name:spotify" }))
  hl.bind("t", hl.dsp.submap("reset"))
  hl.bind("w", hl.dsp.focus({ workspace = "name:whatsapp" }))
  hl.bind("w", hl.dsp.submap("reset"))

  hl.bind("SHIFT + D", hl.dsp.window.move({ workspace = "name:discord" }))
  hl.bind("SHIFT + D", hl.dsp.submap("reset"))
  hl.bind("SHIFT + S", hl.dsp.window.move({ workspace = "name:obs" }))
  hl.bind("SHIFT + S", hl.dsp.submap("reset"))
  hl.bind("SHIFT + O", hl.dsp.window.move({ workspace = "name:obsidian" }))
  hl.bind("SHIFT + O", hl.dsp.submap("reset"))
  hl.bind("SHIFT + A", hl.dsp.window.move({ workspace = "name:anki" }))
  hl.bind("SHIFT + A", hl.dsp.submap("reset"))
  hl.bind("SHIFT + M", hl.dsp.window.move({ workspace = "name:moonlight" }))
  hl.bind("SHIFT + M", hl.dsp.submap("reset"))
  hl.bind("SHIFT + Q", hl.dsp.window.move({ workspace = "name:qutebrowser" }))
  hl.bind("SHIFT + Q", hl.dsp.submap("reset"))
  hl.bind("SHIFT + T", hl.dsp.window.move({ workspace = "name:spotify" }))
  hl.bind("SHIFT + T", hl.dsp.submap("reset"))
  hl.bind("SHIFT + W", hl.dsp.window.move({ workspace = "name:whatsapp" }))
  hl.bind("SHIFT + W", hl.dsp.submap("reset"))

  hl.bind("ESCAPE", hl.dsp.submap("reset"))
end)

hl.bind("SUPER + N", hl.dsp.submap("app"))
