windowrule = noblur, match:class kando
windowrule = opaque, match:class kando
windowrule = size 100% 100%, match:class kando
windowrule = noborder, match:class kando
windowrule = noanim, match:class kando
windowrule = float, match:class kando
windowrule = pin, match:class kando

bind = CTRL, Space, global, menu.kando.Kando:example-menu

env=ELECTRON_OZONE_PLATFORM_HINT,auto
