[pyprland]
plugins = ["scratchpads", "expose"]

# Dropdown terminal
[scratchpads.term]
command = "kitty -o background_opacity=0.5 --class kitty-scratch"
class = "kitty-scratch"
size = "65% 20%"
animation = "fromTop"
unfocus = "hide"

[scratchpads.music]
command = "spotify"
class = "spotify"
size = "70% 80%"
animation = "fromRight"
unfocus = "hide"

[scratchpads.btop]
command = "kitty --class kitty-btop btop --force-utf"
class = "kitty-btop"
size = "70% 80%"
animation = "fromTop"
unfocus = "hide"

[scratchpads.superproductivity]
command = "super-productivity"
class = "superProductivity"
position = "0% 3%"
size = "100% 97%"
animation = "fromTop"
unfocus = "hide"

[scratchpads.qutebrowser]
command = "qutebrowser"
class = "org.qutebrowser.qutebrowser"
position = "0% 3%"
size = "100% 97%"
animation = "fromTop"
unfocus = "hide"

[scratchpads.writer]
command = "kitty -o background_opacity=0.8 --class kitty-writer --directory ~/notes nvim"
class = "kitty-writer"
size = "70% 80%"
animation = "fromTop"
unfocus = "hide"
