# Numbered Workspace switching
bind = SUPER, 1, workspace, 1
bind = SUPER SHIFT, 1, movetoworkspace, 1

bind = SUPER, 2, workspace, 2
bind = SUPER SHIFT, 2, movetoworkspace, 2

bind = SUPER, 3, workspace, 3
bind = SUPER SHIFT, 3, movetoworkspace, 3

bind = SUPER, 4, workspace, 4
bind = SUPER SHIFT, 4, movetoworkspace, 4

bind = SUPER, 5, workspace, 5
bind = SUPER SHIFT, 5, movetoworkspace, 5

# Adjacent Workspace switching
bind = SUPER, left, workspace, prev
bind = SUPER, down, workspace, e-1
bind = SUPER, up, workspace, e+1
bind = SUPER, right, workspace, next

bind = SUPER SHIFT, left, movetoworkspace, prev
bind = SUPER SHIFT, down, movetoworkspace, e-1
bind = SUPER SHIFT, up, movetoworkspace, e+1
bind = SUPER SHIFT, right, movetoworkspace, next

# Scroll through existing workspaces with SUPER + scroll
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Focus
bind = SUPER, semicolon, focuscurrentorlast # prev window
bind = SUPER, slash, workspace, previous # prev workspaces

# Move focus between tiles with vim keys
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r

# Swap windows (move tiles) in tiling mode
bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, j, movewindow, d
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, l, movewindow, r

# Scrolling layout - column navigation
bind = SUPER, period, layoutmsg, move +col
bind = SUPER, comma, layoutmsg, move -col

# Move/resize windows with SUPER + LMB/RMB and dragging
bindm = SUPER, mouse:273, resizewindow
bindm = SUPER, mouse:272, movewindow
