# See https://wiki.hyprland.org/Configuring/Keywords/

# Programs
$terminal = kitty
$fileManager = thunar
$menu = rofi

# APPLICATIONS
bind = SUPER, return, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER, P, exec, scrcpy --render-driver=opengl --turn-screen-off --stay-awake --no-audio

# MENU
bind = SUPER, SPACE, exec, $menu -show combi
bind = SUPER CTRL, PERIOD, exec, $menu -show emoji
bind = SUPER, V, exec, $menu -show cliphist

# UTILIS
# bind = , PRINT, exec, hyprshot -m region --clipboard-only
# bind = shift, PRINT, exec, hyprshot -m window --clipboard-only
bind = SUPER CTRL, P, exec, sh ~/bin/screenshot
bind = SUPER ALT, L, exec, hyprlock
