# Window controls
bind = SUPER, Q, killactive,
bind = SUPER ALT, E, exit,
bind = SUPER ALT, V, togglefloating,
bind = SUPER ALT, J, togglesplit, # dwindle
bind = SUPER, P, pin

bind = SUPER, F, fullscreen, 0