# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Qutebrowser
# windowrulev2 = workspace 20, class:^(org.qutebrowser.qutebrowser)$
# exec-once = qutebrowser
# bind = SUPER, W, workspace, 20
# bind = SUPER SHIFT, W, movetoworkspace, 20
# Notes
# windowrulev2 = workspace 21, class:^(notes)$
# bind = SUPER, N, workspace, 21
# bind = SUPER SHIFT, N, movetoworkspace, 21
# Termusic
# windowrulev2 = workspace 22, class:^(termusic)$
# bind = SUPER, M, workspace, 22
# bind = SUPER SHIFT, M, movetoworkspace, 22
# Btop
# windowrulev2 = workspace 23, class:^(btop)$
# exec-once = kitty --class btop -o confirm_os_window_close=1 -- btop --force-utf
# bind = SUPER, B, workspace, 23
# bind = SUPER SHIFT, B, movetoworkspace, 23
# Whatsapp
windowrule = workspace 24, match:class ^(chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default)$
bind = SUPER, C, workspace, 24
bind = SUPER SHIFT, C, movetoworkspace, 24
# Discord
windowrule = workspace 25, match:class ^(discord)$
bind = SUPER, D, workspace, 25
bind = SUPER SHIFT, D, movetoworkspace, 25
# OBS
windowrule = workspace 26, match:class ^(com.obsproject.Studio)$
bind = ALT, O, workspace, 26
bind = SUPER SHIFT, O, movetoworkspace, 26
# Obsidian
windowrule = workspace 15, match:class ^(obsidian)$
# Anki
windowrule = workspace 16, match:class ^(anki)$
# Moonlight
windowrule = workspace 17, match:class ^(com.moonlight_stream.Moonlight)$
