# utilities
exec-once = waybar
exec-once = nm-applet --indicator
exec-once = swaync
# exec-once = mpvpaper -o "no-audio --loop-playlist --panscan=1.0 --no-keepaspect-window" '*' ~/Wallpapers/cat-in-the-swamp-moewalls-com.mp4

# applications
exec-once = wayneko --layer top
