# Default window layout
general {
    layout = dwindle
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# Toggle pseudotile (keep window as single tile)
bind = SUPER ALT, P, pseudo, # dwindle

# See https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    new_status = master
}
