# Scratchpads - toggle dropdown terminals/applications using pyprland
exec-once = pypr

# Scratchpad toggles
bind = SUPER, T, exec, pypr toggle term
bind = SUPER, M, exec, pypr toggle music
bind = SUPER, B, exec, pypr toggle btop
bind = SUPER, S, exec, pypr toggle superproductivity
bind = SUPER, W, exec, pypr toggle qutebrowser
bind = SUPER, N, exec, pypr toggle writer