# Scratchpads - toggle dropdown terminals/applications using pyprland
# exec-once = pypr

# Scratchpad toggles
# bind = SUPER, T, exec, pypr toggle term
# bind = SUPER, B, exec, pypr toggle btop
# bind = SUPER, N, exec, pypr toggle writer
# bind = SUPER, P, exec, pypr toggle phone
# bind = SUPER, M, exec, pypr toggle music
# bind = SUPER, W, exec, pypr toggle qutebrowser
# bind = SUPER, S, exec, pypr toggle superproductivity
